### ISSUE TITLE
Should change local setup instruction, because MySQL version and password issue

### ISSUE THREAD

**Issue by ddinggu** [jd1386/korean-json#6]
Follow your basic setup instruction, I occurred two error in create db.

1. MySQL version issue  > 8.0 
```
$ node_modules/.bin/sequelize db:create

ERROR: Client does not support authentication protocol requested by server; consider upgrading MySQL client
```
It occurs when I follow your setup instruction and find why it occurs because MySQL uses new authentication plugin [caching_sha2_password](https://dev.mysql.com/doc/refman/8.0/en/sha256-pluggable-authentication.html) but, Node.js driver MySQL don't support this plugin not yet. 
(https://stackoverflow.com/questions/50373427/node-js-cant-authenticate-to-mysql-8-0/50377944#50377944)

So, I alter root user to older authentication plugin for works Sequelize.
```
$ mysql -uroot 

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '<mypassword>';
```

2. MySQL root password incorrect in local and config.json environments
```
$ node_modules/.bin/sequelize db:create

ERROR: Access denied for user 'root'@'localhost' (using password: NO)
```
This error resolve with change development environment password in config.json
```
config/config.js 
{
  "development": {
    "username": "root",
    "password": "<mypassword>",
    "database": "koreanjson_development",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  ...
}
```
And everything is fine. 

I'm not sure this error occurs only to me and those are best solutions, but please consider this issues.

Thank you.

------ 
Environment : 
OS: Mac High Sierra 10.13.6
Node: 10.14.2
Sequelize CLI: 5.4.0
ORM: 4.42.0
mysql: 8.0.15 for osx10.13 on x86_64 (Homebrew)

**Comment by sunnysid3up** [comment]
Same issue happened to me. I had to change the mysql password also to make it work. Make sure to not include the config file changes when you commit :)

**Comment by ddinggu** [comment]
README에 이 이슈에 대한 간단한 안내 추가했으면 좋겠습니다 😄

**Comment by jd1386** [comment]
감사합니다. 각자의 데이터베이스 환경별 아이디와 비밀번호를 넣으라고 안내하도록 하겠습니다.
